# Generated by GitHub Copilot from: mindmaps/sample_login_module.json
# Module: Login Module
# Format: Gherkin (BDD)

Feature: Login Module

  Background:
    Given the application is running
    And the user is on the login screen

  # --- Standard Login ---

  Scenario: Successful login with valid credentials
    Given the user has a registered account with email "testuser@company.com"
    When the user enters email "testuser@company.com" and password "ValidPass@123"
    And the user clicks the Login button
    Then the user should be redirected to the dashboard
    And the session should be active

  Scenario: Login fails with incorrect password
    Given the user has a registered account with email "testuser@company.com"
    When the user enters email "testuser@company.com" and password "WrongPass999"
    And the user clicks the Login button
    Then an error message "Invalid email or password" should be displayed
    And the user should remain on the login screen

  Scenario: Login fails with unregistered email
    When the user enters email "notregistered@company.com" and password "AnyPass@123"
    And the user clicks the Login button
    Then an error message "Invalid email or password" should be displayed

  # --- Business Rules ---

  Scenario: Account is locked after 5 consecutive failed login attempts
    Given the user has a registered account with email "testuser@company.com"
    When the user enters an incorrect password 5 times consecutively
    Then the account should be locked
    And the message "Account locked. Contact support." should be displayed

  Scenario: Login attempt on a locked account
    Given the account "locked.user@company.com" is locked
    When the user attempts to log in with correct credentials
    Then the message "Account locked. Contact support." should be displayed

  Scenario: Session expires after 30 minutes of inactivity
    Given the user is logged in
    When the user is inactive for 30 minutes
    Then the session should expire
    And the user should be redirected to the login screen

  # --- Logout ---

  Scenario: Successful logout
    Given the user is logged in and on the dashboard
    When the user clicks the profile icon
    And the user selects Logout
    Then the session should be terminated
    And the user should be redirected to the login screen

  Scenario: Browser back button after logout should not restore session
    Given the user has logged out
    When the user presses the browser back button
    Then the user should remain on the login screen
    And the session should not be restored

  # --- Forgot Password ---

  Scenario: Password reset email is sent for registered email
    When the user clicks the "Forgot Password" link
    And the user enters the registered email "testuser@company.com"
    And the user submits the reset request
    Then a password reset email should be sent to "testuser@company.com"
    And a confirmation message "Reset link sent to your email" should be displayed

  Scenario: Password reset link expires after 15 minutes
    Given the user has received a password reset link
    When the user opens the reset link after 15 minutes
    Then the message "This link has expired. Request a new one." should be displayed

  # --- Edge Cases ---

  Scenario: Login with leading and trailing spaces in email
    When the user enters email "  testuser@company.com  " and password "ValidPass@123"
    And the user clicks the Login button
    Then the system should trim the email and authenticate successfully

  Scenario: Login with maximum length email
    When the user enters a valid email of 254 characters and correct password
    And the user clicks the Login button
    Then the user should be authenticated successfully

  Scenario: Login on slow network
    Given the network response time is greater than 5 seconds
    When the user submits valid credentials
    Then a loading indicator should be displayed
    And the user should eventually be redirected to the dashboard or shown a timeout error
